---
version: '2'
services:
  zookeeper:
    image: zookeeper:3.6
    command: "bin/zkServer.sh start-foreground"
    network_mode: "host"
    container_name: zookeeper
  kafka:
    image: wurstmeister/kafka:2.13-2.6.0
    command: "start-kafka.sh"
    container_name: kafka
    network_mode: "host"
    environment:
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ZOOKEEPER_CONNECT: localhost:2181
      KAFKA_AUTHORIZER_CLASS_NAME: kafka.security.auth.SimpleAclAuthorizer
      KAFKA_SUPER_USERS: User:admin
      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "true"
      KAFKA_OPTS: -Djava.security.auth.login.config=/opt/kafka/jaas/kafka_server_jaas.conf
    volumes:
      - ./kafka_server_jaas.conf:/opt/kafka/jaas/kafka_server_jaas.conf